name: Example Workflow
 
on: [push]
 
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Create an issue
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo } = context.repo;
          await github.rest.issues.create({
            owner,
            repo,
            title: 'Example issue',
            body: 'This issue was created using GITHUB_TOKEN.'
          });